DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    email varchar(100) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS requests  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(255) NOT NULL,
    requester_id INTEGER references users(id) NOT NULL,
    created_time TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS items  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    description varchar(255) NOT NULL,
    is_available BOOLEAN NOT NULL,
    owner_id INTEGER references users(id) NOT NULL,
    request_id INTEGER references requests(id)
);
CREATE TABLE IF NOT EXISTS bookings  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    item_id INTEGER references items(id) NOT NULL,
    booker_id INTEGER references users(id) NOT NULL,
    status varchar(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS comments  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text_of_comment varchar (255) NOT NULL,
    item_id INTEGER references items(id) NOT NULL,
    author_id INTEGER references users(id) NOT NULL,
    created_time TIMESTAMP NOT NULL
);